# -*- coding: utf-8 -*-
"""SCORE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rnKURTKZzL7C3PGSy0_vfupkOlodiHr1
"""

scores = list(map(int, input().split()))

count = 0

for s in scores:
    if s < 60:
        count += 1

print(count)
print(max(scores))
print(min(scores))