# -*- coding: utf-8 -*-
"""SCORE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJALFCSamFpjMgIfVgzE8QUyKwzvbuPA
"""

scores = list(map(int, input().split()))

count = 0
# 1. 初始化總和變數
total_sum = 0

for s in scores:
    if s < 60:
        count += 1
    # 2. 在迴圈中累加每一個分數
    total_sum += s

# 3. 計算平均值（總和 / 分數個數）
# 注意：若輸入為空，需考慮除以零的錯誤處理
if len(scores) > 0:
    average = total_sum / len(scores)
else:
    average = 0

print(f"不及格人數: {count}")
print(f"平均分數: {average:.2f}") # :.2f 表示格式化到小數點後兩位